on:
  schedule:
    - cron: '1 */12 * * *' # every 12 hours
  push:
    branches:
      - profile-readme-stats
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update profile README stats
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name ernir
          git config user.email e.ernir@gmail.com
          git add .
          git commit -m "Update profile README stats"
          git push
          fi
